plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.zelix_rised_trades'
    compileSdk 35

    defaultConfig {
        applicationId 'com.zelix_rised_trades'
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildFeatures {
        prefab true
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.games:games-activity:4.0.0'
}
